version: '3'
services:

  db:
    image: "mysql:latest"
    container_name: eatnow_database
    volumes:
      - mysql-data:/var/lib/mysql6/data2
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  backend:
    image: "sibindockerhub/eatnow-backend:ver1"
    container_name: eatnow_backend
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/eatnowdb?createDatabaseIfNotExist=true
    ports:
      - 8090:8090

  frontend:
    image: "sibindockerhub/eatnow-frontend:ver1"
    container_name: eatnow_frontend
    ports:
      - 4200:3000


volumes:
  mysql-data:
